from __future__ import annotations

import os
import re
import uuid
from io import BytesIO
from typing import Any

import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.encoders import jsonable_encoder
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from pydantic import BaseModel, Field
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from ops_copilot import __version__
from ops_copilot.data_loader import load_workbook
from ops_copilot.insights import InsightReport, generate_executive_insight_report
from ops_copilot.models import QueryResult, SemanticQuery
from ops_copilot.postgres_loader import ensure_postgres_loaded
from ops_copilot.query_engine import QueryEngine, QueryValidationError
from ops_copilot.settings import default_data_file, export_dir

app = FastAPI(
    title="Rappi Ops Copilot API",
    version=__version__,
    description="Analytics API used by the n8n Rappi Ops Copilot workflow.",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

_ENGINE: QueryEngine | None = None
_RESULT_CACHE: dict[str, QueryResult | "SqlQueryResult"] = {}
_INSIGHT_REPORT_CACHE: InsightReport | None = None
_WRITE_SQL_RE = re.compile(
    r"\b(alter|analyze|call|comment|copy|create|delete|do|drop|execute|grant|insert|"
    r"merge|refresh|reindex|revoke|truncate|update|vacuum)\b",
    re.IGNORECASE,
)


class SchemaRequest(BaseModel):
    include_examples: bool = True
    language: str = "es"


class SqlQueryRequest(BaseModel):
    question: str = ""
    sql: str
    limit: int = Field(default=200, ge=1, le=1000)
    visualization: str = "auto"


class SqlQueryResult(BaseModel):
    query_id: str
    question: str
    sql: str
    columns: list[str]
    rows: list[dict[str, Any]]
    row_count: int
    truncated: bool
    visualization_hint: str
    caveats: list[str] = Field(default_factory=list)
    suggested_followups: list[str] = Field(default_factory=list)


class GenerateInsightsRequest(BaseModel):
    source: str = "api"
    persist: bool = True


@app.on_event("startup")
def startup_load_postgres() -> None:
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        ensure_postgres_loaded(database_url, default_data_file())


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "version": __version__}


@app.get("/schema")
def schema_get(include_examples: bool = True) -> dict[str, Any]:
    return _engine().schema(include_examples=include_examples)


@app.post("/schema")
def schema_post(request: SchemaRequest) -> dict[str, Any]:
    return _engine().schema(include_examples=request.include_examples)


@app.post("/query", response_model=QueryResult)
def query(request: SemanticQuery) -> QueryResult:
    try:
        result = _engine().execute(request)
    except QueryValidationError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    _RESULT_CACHE[result.query_id] = result
    return result


@app.post("/sql", response_model=SqlQueryResult)
def run_sql(request: SqlQueryRequest) -> SqlQueryResult:
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise HTTPException(status_code=503, detail="DATABASE_URL is not configured.")

    sql = _clean_read_only_sql(request.sql)
    wrapped_sql = f"select * from ({sql}) as model_query limit %s"

    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:
        raise HTTPException(status_code=503, detail="psycopg is not installed.") from exc

    try:
        with psycopg.connect(database_url, row_factory=dict_row) as conn:
            conn.read_only = True
            with conn.cursor() as cur:
                cur.execute("set local statement_timeout = '20s'")
                cur.execute(wrapped_sql, (request.limit + 1,))
                fetched = cur.fetchall()
    except Exception as exc:
        raise HTTPException(status_code=422, detail=f"SQL execution failed: {exc}") from exc

    rows = [jsonable_encoder(dict(row)) for row in fetched[: request.limit]]
    truncated = len(fetched) > request.limit
    columns = list(rows[0].keys()) if rows else []
    result = SqlQueryResult(
        query_id=str(uuid.uuid4()),
        question=request.question,
        sql=sql,
        columns=columns,
        rows=rows,
        row_count=len(rows),
        truncated=truncated,
        visualization_hint=request.visualization,
        caveats=[
            "SQL was generated by the model and executed read-only against Postgres.",
            "L0W is the most recent available week, not a calendar date.",
        ],
        suggested_followups=[
            "Ask for the same analysis by city or zone.",
            "Ask for a trend over the last 8 weeks.",
            "Ask to export this result to CSV or PDF.",
        ],
    )
    _RESULT_CACHE[result.query_id] = result
    return result


@app.post("/insights/generate", response_model=InsightReport)
def generate_insights(request: GenerateInsightsRequest) -> InsightReport:
    return _generate_and_store_insights(source=request.source, persist=request.persist)


@app.get("/insights/latest", response_model=InsightReport)
def latest_insights() -> InsightReport:
    report = _load_latest_insight_report()
    if report:
        return report
    if _INSIGHT_REPORT_CACHE:
        return _INSIGHT_REPORT_CACHE
    return _generate_and_store_insights(source="api_on_demand", persist=True)


@app.get("/insights/latest.md")
def latest_insights_markdown() -> Response:
    report = latest_insights()
    return Response(
        content=report.markdown,
        media_type="text/markdown",
        headers={
            "Content-Disposition": f'inline; filename="{report.report_id}-executive-insights.md"'
        },
    )


@app.get("/exports/{query_id}.csv")
def export_csv(query_id: str) -> Response:
    result = _cached_result(query_id)
    frame = pd.DataFrame(result.rows)
    csv_text = frame.to_csv(index=False)
    return Response(
        content=csv_text,
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{query_id}.csv"'},
    )


@app.get("/exports/{query_id}.pdf")
def export_pdf(query_id: str) -> Response:
    result = _cached_result(query_id)
    payload = _build_pdf(result)
    return Response(
        content=payload,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{query_id}.pdf"'},
    )


def _engine() -> QueryEngine:
    global _ENGINE
    if _ENGINE is None:
        _ENGINE = QueryEngine(load_workbook(default_data_file()))
    return _ENGINE


def _cached_result(query_id: str) -> QueryResult | SqlQueryResult:
    result = _RESULT_CACHE.get(query_id)
    if result is None:
        raise HTTPException(
            status_code=404,
            detail="Unknown query_id. Export is available only for results produced since API startup.",
        )
    return result


def _generate_and_store_insights(source: str, persist: bool) -> InsightReport:
    global _INSIGHT_REPORT_CACHE
    report = generate_executive_insight_report(_engine().dataset, source=source)
    _INSIGHT_REPORT_CACHE = report
    _write_insight_report_files(report)
    if persist:
        _store_insight_report(report)
    return report


def _store_insight_report(report: InsightReport) -> None:
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        return
    try:
        import psycopg
        from psycopg.types.json import Jsonb
    except ImportError:
        return

    payload = report.model_dump(mode="json")
    try:
        with psycopg.connect(database_url) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    insert into executive_insight_report (
                      report_id, source, period_label, report_markdown, report_json
                    )
                    values (%s, %s, %s, %s, %s::jsonb)
                    on conflict (report_id) do update set
                      source = excluded.source,
                      period_label = excluded.period_label,
                      report_markdown = excluded.report_markdown,
                      report_json = excluded.report_json
                    """,
                    (
                        report.report_id,
                        report.source,
                        report.period_label,
                        report.markdown,
                        Jsonb(jsonable_encoder(payload)),
                    ),
                )
            conn.commit()
    except Exception as exc:
        raise HTTPException(status_code=503, detail=f"Could not store insight report: {exc}") from exc


def _load_latest_insight_report() -> InsightReport | None:
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        return None
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError:
        return None

    try:
        with psycopg.connect(database_url, row_factory=dict_row) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    select report_json
                    from executive_insight_report
                    order by created_at desc
                    limit 1
                    """
                )
                row = cur.fetchone()
    except Exception:
        return None
    if not row:
        return None
    return InsightReport.model_validate(row["report_json"])


def _write_insight_report_files(report: InsightReport) -> None:
    directory = export_dir() / "reports"
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "latest-executive-insights.md").write_text(report.markdown, encoding="utf-8")
    (directory / "latest-executive-insights.json").write_text(
        report.model_dump_json(indent=2),
        encoding="utf-8",
    )


def _clean_read_only_sql(sql: str) -> str:
    cleaned = sql.strip()
    if not cleaned:
        raise HTTPException(status_code=422, detail="SQL is required.")
    cleaned = cleaned.rstrip(";").strip()
    if ";" in cleaned:
        raise HTTPException(status_code=422, detail="Only one SQL statement is allowed.")
    if not re.match(r"^(select|with)\b", cleaned, re.IGNORECASE):
        raise HTTPException(status_code=422, detail="Only SELECT or WITH queries are allowed.")
    if _WRITE_SQL_RE.search(cleaned):
        raise HTTPException(status_code=422, detail="Write or administrative SQL is not allowed.")
    if "--" in cleaned or "/*" in cleaned or "*/" in cleaned:
        raise HTTPException(status_code=422, detail="SQL comments are not allowed.")
    return cleaned


def _build_pdf(result: QueryResult | SqlQueryResult) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, title="Rappi Ops Copilot Result")
    styles = getSampleStyleSheet()
    answer_type = getattr(result, "answer_type", "model_sql")
    period_label = getattr(result, "period_label", "Model-generated SQL result")
    story: list[Any] = [
        Paragraph("Rappi Ops Copilot Result", styles["Title"]),
        Paragraph(f"Query ID: {result.query_id}", styles["Normal"]),
        Paragraph(f"Answer type: {answer_type}", styles["Normal"]),
        Paragraph(f"Period: {period_label}", styles["Normal"]),
        Spacer(1, 12),
    ]

    if result.caveats:
        story.append(Paragraph("Caveats", styles["Heading2"]))
        for caveat in result.caveats:
            story.append(Paragraph(f"- {caveat}", styles["Normal"]))
        story.append(Spacer(1, 12))

    story.append(Paragraph("Rows", styles["Heading2"]))
    rows = result.rows[:40]
    if not rows:
        story.append(Paragraph("No rows returned.", styles["Normal"]))
    else:
        columns = list(rows[0].keys())[:8]
        table_data = [columns]
        for row in rows:
            table_data.append([_pdf_cell(row.get(column)) for column in columns])
        table = Table(table_data, repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 7),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D1D5DB")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.append(table)

    doc.build(story)
    return buffer.getvalue()


def _pdf_cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4g}"
    return str(value)[:80]
